### PR TITLE
Rename OtrStore file in otr-store

### PR DESCRIPTION
**Pull request by astorije**
`file-name.js` is the _de facto_ standard in the Node / JavaScript world. Of course, there is no auto-loading so it just is what it is, a convention. But it's nice to blend in, after all :-)

(Yes, I noticed there is sadly a `clientManager.js` file, alone in the dark...)

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
> (Yes, I noticed there is sadly a clientManager.js file, alone in the dark...)

So… Then… It's the convention for this project, and the convention for naming files in js seem not to be very bold. Just for my own curiosity (because I'm looking for conventions in js, as I'm new with that language), I picked two js project I use happen to use daily, which are quite big ones :

https://git.popcorntime.io/popcorntime/desktop/tree/development/src/app/lib/models

`favorite_collection.js`

https://github.com/ether/etherpad-lite/tree/develop/src/node/db

`GroupManager.js`

So I guess different file naming conventions are running out there and there is no good reason to change the one chosen in shout. What do you think ?

**Comment by JocelynDelalande** [comment]
But you raised my awareness on`otrmessage.js` which is following [slate-irc convention](https://github.com/slate/slate-irc/tree/master/lib/plugins) which might be a bad idea (as this code is not from slate-irc, even if adopting the plugins mechanism and `require` the lib)

**Comment by astorije** [comment]
Indeed, there are plenty of things around and that's sad, but oh well.

Now, a rationale about `file-name.js`: In terms of project name convention, pretty much all npm packages are `project-name`: https://www.npmjs.com/. In practice, when you want to import a package, you do `require('project-name')`. But you can also import files with `require('./file-name'). So, even though there is no official convention around file names, when you do things nicely and want to have consistent naming across your project, files, imported projects, imported files, ... choosing`file-name.js` gives you peace of mind :-)
You generally want to use the same convention for folders because you can import files or folders the same way.

That being said, I could only find three examples across the entire project that were not made of a single word (like `msg.js`):
- `command-line` and `irc-events` folders
- `clientManager.js`

Which proves that there is no set convention in shout yet (meaning one will have to be enforced at the moment) and that `FileName.js` as you named your `OtrStore.js` isn't among the examples.

My PR proposes `otr-store.js`, in which case I'll be PR'ing the main project on `clientManager.js` if this gets adopted, to be consistent project-wise since there is only 1 exception (not like there is an entire project to adapt). If this doesn't suit you, I propose `otrStore.js` and no PR on the main project.
I'm sure you'll have my preference, but it's up to you :-)

**Comment by JocelynDelalande** [comment]
(so much talk for a caps :p)

> If this doesn't suit you, I propose otrStore.js and no PR on the main project.

I'd go for that.

Rationale is this discussion should not take place on that fork but on source project, so let's stick to the closest case we can find for that usage in the project (`clientManager.js` is the best match), and have style conversations in parent project.

**Comment by JocelynDelalande** [comment]
I suggest we create a new word : _"capstalk"_, a specialized form of _"bikesheding"_ :)

**Comment by astorije** [comment]
Well, there would not be any bikeshedding if you had just accepted my first offer... :-)

**Comment by astorije** [comment]
I wish you would have gone for the other solution, but nevermind, amended my comment, please :+1: it.

**Comment by JocelynDelalande** [comment]
All right :)

BTW thanks for pointers and discussion on naming conventions in JS. I'm loving bikesheding teaching side-effects.

**Comment by JocelynDelalande** [comment]
Actually… you should reword your commit, then get my :+1: and feel free to merge :)

**Comment by astorije** [comment]
Fuuuuuuuuuuuuuu

**Pull request merged**
