### PR TITLE
Fix chan creation when first message is otr msg

### LINKED ISSUE #5: otr init is crashing if started from remote side while no query tab is opened in shout UI

### PR DESCRIPTION
**Pull request by JocelynDelalande**
Fixes #5

### CODE REVIEW

**Comment by astorije** [comment]
I'm pretty much OK with this PR, good job! One comment before I give my :+1:: it seems odd that `startQuery` is in the `Client`'s prototype while `getQuery` is in the `Network`'s prototype.
Shouldn't/Couldn't we make this nicer by bundling these similar functions together?

(One could DRY up a bit more - too much maybe - by adding `createOrStartQuery` after that, but that's not the main concern of my comment)

**Comment by JocelynDelalande** [comment]
> I'm pretty much OK with this PR, good job! One comment before I give my :+1:: it seems odd that startQuery is in the Client's prototype while getQuery is in the Network's prototype.
> Shouldn't/Couldn't we make this nicer by bundling these similar functions together?

Yep, I do agree, my rationale was :
- the logic would like that both of those methods are supposed to be encapsulated inside `Network`
- …but `startQuery()` requires to emit an event from client, which you can't (or you don't want to) do from `Network`.

A complicated solution would be to add events to network, but it escapes the scope of the PR, as it would require to touch more of the code to remain consistant. Furthermore, that will be a lot of event handling for a small quantity of code (= harder to read & debug). 

So I'm going to move both methods to `Client`, simply.

**Comment by JocelynDelalande** [comment]
@astorije ok with that ?

**Comment by astorije** [comment]
> A complicated solution would be to add events to network, but it escapes the scope of the PR, as it would require to touch more of the code to remain consistant. Furthermore, that will be a lot of event handling for a small quantity of code (= harder to read & debug).

Yes, events are fun to add, and a huge pain in the butt to debug and maintain. I also noticed that after a certain point, events are the trash bin when you don't know where to put something because you have to keep design and encapsulation in mind.

Anyway, yes, I :+1: :-)

**Pull request merged**
